#+TITLE: Pget - .NET Command Line toolbox and Interface for NuGet.Core and F#
#+AUTHOR: Caio Rodrigues
#+EMAIL:  caiorss [DOT] rodrigues [DOT] gmail [DOT] com
#+DESCRIPTION: F# Command line interface to NuGet API.
#+STARTUP: content
#+KEYWORDS: NuGet F# fsharp csharp .net dotnet tool cli command line toolbox

* Pget.exe - Package Get
** Overview

Pget.exe is high level wrapper to NuGet.core package which provides
command line tools to manage dependencies in F# projects or .NET projects.

Objective: Provide NuGet.Core integration with external tools, text editors
like Emacs and also command line integration with NuGet API.


Features:

 - Search  packages in Nuget repository


 - Install NuGet packages


 - Display all assembly references in a repository


 - Show details about packages like description, summary, web site and so on.


 - Inspect .NET assemblies.
   - Show .NET assemblies metadata
   - Show .NET referenced assemblies


 - Show NuGet packages *.nupkg file metadata.


 - Get packages' assembly references from local repository and project
   repository (./packages) for F# scripts.

** Build instructions
*** Build with Makefile

Run the command =$ make exe=. It assumes that fsc - the F# compiler
and nuget.exe are in the $PATH variable. It builds the standlone app
pget.exe with all dependencies static linked and also FSharp.Core (F#
runtime) static linked.

#+BEGIN_SRC sh
  $ make exe
  fsc src/Pget.fs src/PgetCmd.fsx --out:bin/pget.exe \
  --target:exe \
      --platform:anycpu \
      -r:packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll \
  -r:packages/Microsoft.Web.Xdt.2.1.1/lib/net40/Microsoft.Web.XmlTransform.dll \
  --staticlink:NuGet.Core \
  --standalone
  F# Compiler for F# 4.1
  Freely distributed under the Apache 2.0 Open Source License

#+END_SRC

Testing:

#+BEGIN_SRC sh
  $ file bin/pget.exe
  bin/pget.exe: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows

  $ bin/pget.exe --version

      Pget - Package Get - Version 1.0
      Copyright (C) 2016 Caio Rodrigues
#+END_SRC

*** Build with Xbuild or Msbuild

 - =$ xbuild pget-exe.fsproj=

Unfortunally is not possible yet to build an standalone app with xbuild.

#+BEGIN_SRC sh
  $ tree bin/
  bin/
  └── Debug
      ├── FSharp.Core.dll
      ├── Microsoft.Web.XmlTransform.dll
      ├── NuGet.Core.dll
      ├── Pget.exe
      └── Pget.exe.mdb

  1 directory, 5 files


  $ bin/Debug/Pget.exe --version

      Pget - Package Get - Version 1.0
      Copyright (C) 2016 Caio Rodrigues

#+END_SRC

** Get binary release

The binary releases are published to orphan-branch [[https://github.com/caiorss/pget/tree/build][build]]. 

*Manual download*

 - [[https://github.com/caiorss/pget/raw/build/pget.exe][Download pget.exe]]

*Automatic Download* 

#+BEGIN_SRC sh 
  ~/Downloads $ curl -O -L https://github.com/caiorss/pget/raw/build/pget.exe
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   127  100   127    0     0    169      0 --:--:-- --:--:-- --:--:--   169
  100 2143k  100 2143k    0     0   257k      0  0:00:08  0:00:08 --:--:--  529k
  ~/Downloads $


  ~/Downloads $ /usr/bin/chmod +x pget.exe

  ~/Downloads $ ./pget.exe -v 

      Pget - Package Get - Version 1.0 
      Copyright (C) 2016 Caio Rodrigues        
#+END_SRC

or 

#+BEGIN_SRC sh 
  cd ~/bin 
  curl -O -L https://github.com/caiorss/pget/raw/build/pget.exe
  /usr/bin/chmod +x pget.exe
  ./pget.exe -v 
#+END_SRC

** Install
** Commands
*** Print help

 - =$ pget.exe=

#+BEGIN_SRC txt
  $ bin/pget.exe

      Pget - Package Get - Enhanced command line interface to NuGet.Core

      Commands                                    Description
      ------------------------------------------  -------------------------------------------------------------

      List Commands:

        --list                                      List all packages in current repository ./package
        --list [repo]                               List all package in [repo] repository.

        --show                                      Show all packages in current ./packages repository
        --show [repo]                               Show all packages in [repo] repository.
        --show --pack [pack]                        Show the package [pack] in ./packages directory
        --show [repo] --pack [pack]                 Show the package [pack] in [repo] directory.

      Search commands:

        --search [package]                          Search a package by name.
        --search [package] --repo                   Search a pacakge by name in a local repository
        --search [package] --repo [repo]            Search a package in ./packages

      Show references for F# *.fsx scripts:

        --ref [frm]                                 Show all assembly references from current ./packages.
        --ref [frm] --repo [repo]                   Show all assembly references from current [repo] directory.
        --ref [frm] --pack [pack]                   Show all assembly references from a package [pack] at ./packages.
        --ref [frm] --pack [pack] --repo [path]     Show all assembly references from a package at [repo] directory
                                                    frm:  .NET Framework  net40 | net45

      Install packages:

        --install [pack]                            Install the latest version of package [pack] to ./packages
        --install [pack] --repo [repo]              Install the latest version of package [pack] to a repository [repo] i.e: ~/nuget
        --install [pack] --ver [ver]                Install the version [ver] of package [pack]
        --install [pack] --ver [ver] --repo [repo]  Install the version [ver] of package [pack] to a repository [repo]

        --install-from-file                         Install all packages listed in the file ./packages.lst to ./packages directory.
        --install-from-file [file]                  Install all packages listed in the file [file] to ./packages
        --install-from-file [file] --repo [repo]    Install all packages listed in the file [file] to [repo] directory.

      Nupkg Files:

        --nupkg show [file]                         Show metadata of a *.nupkg file

      Assembly files: *.exe or *.dll

        asm show     [file]                         Show all assembly attributes from an assembly file.
        asm show-ref [file]                         Show all assembly references from an assembly file.

      Generate Guid - Globally Unique Identifier

        --guid

      --------------------------------------------------------------------------------------------------------------------

      Command abbreviations:

        --install            -i
        --repo               -r
        --help               -h
        --version            -v
        --ver                -v
        --list               -l
        --search             -s
        --show               -sh
        --install-from-file  -if


      Pget - Package Get - Version 1.0
      Copyright (C) 2016 Caio Rodrigues

#+END_SRC

*** Print Version

 - =$ pget.exe --version= or =$ pget.exe -v=

#+BEGIN_SRC sh
  $ bin/pget.exe --version

      Pget - Package Get - Version 1.0
      Copyright (C) 2016 Caio Rodrigues
#+END_SRC

*** List packages

List packages in current repository ./packages directory:

 - =$ pget.exe --list= or =$ pget.exe -l=

#+BEGIN_SRC sh
  $ bin/pget.exe -l
  Microsoft.Web.Xdt 2.1.1
  NuGet.Core 2.12.0


  $ tree packages
  packages
  ├── Microsoft.Web.Xdt.2.1.1
  │   ├── lib
  │   │   └── net40
  │   │       └── Microsoft.Web.XmlTransform.dll
  │   └── Microsoft.Web.Xdt.2.1.1.nupkg
  └── NuGet.Core.2.12.0
      ├── lib
      │   └── net40-Client
      │       └── NuGet.Core.dll
      └── NuGet.Core.2.12.0.nupkg

  6 directories, 4 files
#+END_SRC

List packages in a directory:

 - =$ pget.exe --list [directory]= or =$ pget.exe --l [directory]=

#+BEGIN_SRC sh
  $ bin/pget.exe -l /home/arch/nuget
  Common.Logging 2.1.2
  Deedle 1.2.5
  Deedle.RPlugin 1.2.5
  DynamicInterop 0.7.4
  EntityFramework 6.0.0
  Eto.Forms 2.2.0
  Eto.Platform.Gtk 2.2.0
  Eto.Platform.Gtk3 2.2.0
  FAKE 4.39.0
  ...
#+END_SRC

*** Show package metadata

Show all packages in ./packages directory

 - =$ pget.exe --show= or =$ pget.exe -sh=

#+BEGIN_SRC txt
  $ bin/pget.exe --show

  Id             Microsoft.Web.Xdt
  Title          Microsoft Xml Document Transformation
  Tags
  Version        2.1.1
  Summary        Microsoft Xml Document Transformation (XDT) enables transformig XML files. This is the same technology used to transform web.config files for Visual Studio web projects.
  Authors        Microsoft Corporation
  Project URL
  Dependencies
  Download Count -1

  Description    Microsoft Xml Document Transformation (XDT) library. For more info on XDT please visit http://msdn.microsoft.com/en-us/library/dd465326.aspx.


  Id             NuGet.Core
  Title
  Tags            nuget
  Version        2.12.0
  Summary
  Authors        Outercurve Foundation
  Project URL    https://github.com/NuGet/NuGet2
  Dependencies   Microsoft.Web.Xdt 2.1.0
  Download Count -1

  Description    NuGet.Core is the core framework assembly for NuGet that the rest of NuGet builds upon.

#+END_SRC

Show all packages in a directory

#+BEGIN_SRC txt
  Id             Common.Logging
  Title
  Tags
  Version        2.1.2
  Summary
  Authors        Aleksandar Seovic,  Mark Pollack,  Erich Eichinger,  Stephen Bohlen
  Project URL    http://netcommon.sourceforge.net/
  Dependencies
  Download Count -1

  Description    Common.Logging library introduces a simple abstraction to allow you to select a specific logging implementation at runtime.

  ...
  ...

  Id             EntityFramework
  Title          EntityFramework
  Tags            Microsoft EF Database Data O/RM ADO.NET
  Version        6.0.0
  Summary        Entity Framework is Microsoft's recommended data access technology for new applications.
  Authors        Microsoft
  Project URL    http://go.microsoft.com/fwlink/?LinkID=320540
  Dependencies
  Download Count -1

  Description    Entity Framework is Microsoft's recommended data access technology for new applications.


#+END_SRC

Show a single package in ./packages (Project repository)

 - =$ pget.exe --show --pack [package-Id]= or - =$ pget.exe -sh -p [package-Id]=

#+BEGIN_SRC sh
  $ bin/pget.exe --show --pack NuGet.Core

  Id             NuGet.Core
  Title
  Tags            nuget
  Version        2.12.0
  Summary
  Authors        Outercurve Foundation
  Project URL    https://github.com/NuGet/NuGet2
  Dependencies   Microsoft.Web.Xdt 2.1.0
  Download Count -1

  Description    NuGet.Core is the core framework assembly for NuGet that the rest of NuGet builds upon.
#+END_SRC


Show a single package in a directory (Local Repository):

 - =$ pget.exe [repository] --show --pack [package-Id]=

or

 - =$ pget.exe -sh [repository] -p [package-Id]=

#+BEGIN_SRC txt
  $ bin/pget.exe --show ~/nuget --pack NUnit.Console

  Id             NUnit.Console
  Title          NUnit Console Runner Version 3 Plus Extensions
  Tags            nunit test testing tdd runner
  Version        3.5.0
  Summary        Console runner for the NUnit 3 unit-testing framework with selected extensions.
  Authors        Charlie Poole
  Project URL    http://nunit.org/
  Dependencies   NUnit.ConsoleRunner 3.5.0, NUnit.Extension.NUnitProjectLoader 3.5.0, NUnit.Extension.VSProjectLoader 3.5.0, NUnit.Extension.NUnitV2ResultWriter 3.5.0, NUnit.Extension.NUnitV2Driver 3.5.0, NUnit.Extension.TeamCityEventListener 1.0.2
  Download Count -1

  Description    This package includes the nunit3-console runner and test engine for version 3.0 of the NUnit unit-testing framework.

        The following extensions are included with this package:
        ,* NUnitProjectLoader     - loads tests from NUnit projects
        ,* VSProjectLoader        - loads tests from Visual Studio projects
        ,* NUnitV2ResultWriter    - saves results in NUnit V2 format.
        ,* NUnitV2FrameworkDriver - runs NUnit V2 tests.
        ,* TeamCityEventListener - supports special progress messages used by teamcity.

        Other extensions, if needed, must be installed separately
#+END_SRC

*** Search a package

 - =$ pget.exe --search [keyword]= or - =$ pget.exe -s [keywork]=

#+BEGIN_SRC txt
  $ bin/pget.exe -s oxyplot

  Id             AnnotationGUIOxyplot
  Title
  Tags
  Version        0.0.1
  Summary
  Authors        tschwarz
  Project URL
  Dependencies
  Download Count 68

  Description    My package description.


  Id             Eto.OxyPlot
  Title          Eto.OxyPlot
  Tags
  Version        1.2.0-beta
  Summary
  Authors        Loren Van Spronsen
  Project URL
  Dependencies   Eto.Forms 2.2.0, OxyPlot.Core 1.0.0-unstable2063
  Download Count 3382

  Description    OxyPlot bindings for the Eto UI framework

 ... ... ...
#+END_SRC
*** Install a package

Install the lastest version of a package to ./packages (Project repository)

 - =$ pget.exe --install [package-id]= or - =$ pget.exe -i [package-id]=

#+BEGIN_SRC sh
  $ bin/pget.exe --install OxyPlot.Pdf
  Installing: OxyPlot.Pdf 1.0.0

  $ ls -l packages
  total 0
  drwxrwxrwx 1 arch arch 280 dez 19 00:52 Microsoft.Web.Xdt.2.1.1/
  drwxrwxrwx 1 arch arch 264 dez 19 01:45 NuGet.Core.2.12.0/
  drwxrwxrwx 1 arch arch 488 dez 19 02:22 OxyPlot.Core.1.0.0/
  drwxrwxrwx 1 arch arch 480 dez 19 02:22 OxyPlot.Pdf.1.0.0/
  drwxrwxrwx 1 arch arch 296 dez 19 02:22 PDFsharp-MigraDoc-GDI.1.32.4334.0/

   bin/pget.exe -sh -p OxyPlot.Core

  Id             OxyPlot.Core
  Title          OxyPlot core library (PCL)
  Tags            plotting plot charting chart
  Version        1.0.0
  Summary
  Authors        Oystein Bjorke
  Project URL    http://oxyplot.org/
  Dependencies
  Download Count -1

  Description    OxyPlot is a plotting library for .NET. This is the portable core library that is referenced by the platform-specific OxyPlot packages.

#+END_SRC

Install a given version of package  to ./packages

 - =$ pget.exe --install [package-id] --version [version]=

or

 - =$ pget.exe -i [package-id] --v [version]=

#+BEGIN_SRC sh
  $ bin/pget.exe -i FParsec -v 1.0.2

  $ ls -l packages
  total 0
  drwxrwxrwx 1 arch arch 256 dez 19 02:31 FParsec.1.0.2/
  drwxrwxrwx 1 arch arch 280 dez 19 00:52 Microsoft.Web.Xdt.2.1.1/
  drwxrwxrwx 1 arch arch 264 dez 19 01:45 NuGet.Core.2.12.0/
  drwxrwxrwx 1 arch arch 488 dez 19 02:22 OxyPlot.Core.1.0.0/
  drwxrwxrwx 1 arch arch 480 dez 19 02:22 OxyPlot.Pdf.1.0.0/
  drwxrwxrwx 1 arch arch 296 dez 19 02:22 PDFsharp-MigraDoc-GDI.1.32.4334.0/
#+END_SRC

Install the lastest version of a package to a local repository

 - =$ pget.exe --install [package-id] --repo [repository]=

or

 - =$ pget.exe -i [package-id] -r [repository]=

#+BEGIN_SRC sh
  $ bin/pget.exe -i  OxyPlot.Pdf -r /home/arch/nuget
  Installing: OxyPlot.Pdf 1.0.0

  $ bin/pget.exe -sh /home/arch/nuget -p OxyPlot.Pdf

  Id             OxyPlot.Pdf
  Title          OxyPlot PDF extensions (for Silverlight and NET4)
  Tags            pdf plotting plot charting chart
  Version        1.0.0
  Summary
  Authors        Oystein Bjorke
  Project URL    http://oxyplot.org/
  Dependencies   OxyPlot.Core [1.0.0], PDFsharp-MigraDoc-GDI [1.32.4334], OxyPlot.Core [1.0.0], PDFsharp-MigraDoc-GDI [1.32.4334], OxyPlot.Core [1.0.0]
  Download Count -1

  Description    OxyPlot is a plotting library for .NET. This package contains .pdf export extensions for .NET 4 (based on PDFsharp) and Silverlight (based on SilverPDF).

#+END_SRC

Install a given version of package to a local repository

 - =$ pget.exe --install [package-id] --version [package] --repo [repository]=

or

 - =$ pget.exe -i [package-id] -v [package] --r [repository]=

#+BEGIN_SRC sh
  $ bin/pget.exe -i Microsoft.Web.Xdt -v 1.0.0 -r ~/nuget
#+END_SRC

Install all packages listed in the file ./packages.list to ./packages

 - =$ pget.exe --install-from-file=

or

 - =$ pget.exe -if=

Example of the file packages.list. If the version is not listed, it
installs the latest version of the packages to ./packages.

File: packages.list

#+BEGIN_SRC sh
  FSharp.Data              1.0.0
  Deedle                   1.0.0
  OxyPlot.Pdf
  OxyPlot.WindowsForms
#+END_SRC

Install all packages listed in the file ./packages.list to ./packages

 - =$ pget.exe --install-from-file [packages-list-file]=

or

 - =$ pget.exe -if [package-list-file]=

*** Get assembly references for F# scripts

Get all assembly references from current ./packages repository.

 - =$ pget.exe --ref [framework]=

The framework is the .NET framework version. It can be:

 - net40 for .NET 4.0
 - net45 for .NET 4.5

#+BEGIN_SRC sh
  $ bin/pget.exe --ref net40
  #r "packages/FParsec.1.0.2/lib/net40-client/FParsec.dll"
  #r "packages/FParsec.1.0.2/lib/net40-client/FParsecCS.dll"
  #r "packages/Microsoft.Web.Xdt.2.1.1/lib/net40/Microsoft.Web.XmlTransform.dll"
  #r "packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll"
  #r "packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.dll"
  #r "packages/OxyPlot.Pdf.1.0.0/lib/net40/OxyPlot.Pdf.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.DocumentObjectModel.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.Rendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.RtfRendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.Charting.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.DocumentObjectModel.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.Rendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.RtfRendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.Charting.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.resources.dll"


  $ bin/pget.exe --ref net45
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"
  #r "packages/Microsoft.Web.Xdt.2.1.1/lib/net40/Microsoft.Web.XmlTransform.dll"
  #r "packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll"
  #r "packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.dll"
  #r "packages/OxyPlot.Pdf.1.0.0/lib/net40/OxyPlot.Pdf.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.DocumentObjectModel.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.Rendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.RtfRendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.Charting.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.DocumentObjectModel.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.Rendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.RtfRendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.Charting.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.resources.dll"



#+END_SRC


Get all assembly references from a package in ./packages:

 - =$ pget.exe --ref [framework] --pack [package-id]=

or

 - =$ pget.exe --ref [framework] --p [package-id]=

#+BEGIN_SRC sh
  $ bin/pget.exe --ref net45 --pack FParsec
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"
#+END_SRC


Get all assembly references from a repository.

 - =$ pget.exe --ref [framework] --repo [repository]=

or

 - =$ pget.exe --ref [framework] -r [repository]=

#+BEGIN_SRC sh
  $ bin/pget.exe -i FSharp.Data -r /tmp/packages
  Installing: FSharp.Data 2.3.2

  $ bin/pget.exe -i FParsec -r /tmp/packages
  Installing: FParsec 1.0.2


  $ ls /tmp/packages/
  FParsec.1.0.2/  FSharp.Data.2.3.2/  Zlib.Portable.1.11.0/

  $ bin/pget.exe --ref net40 --repo /tmp/packages
  #r "/tmp/packages/FParsec.1.0.2/lib/net40-client/FParsec.dll"
  #r "/tmp/packages/FParsec.1.0.2/lib/net40-client/FParsecCS.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/net40/FSharp.Data.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/net40/FSharp.Data.DesignTime.dll"
  #r "/tmp/packages/Zlib.Portable.1.11.0/lib/portable-net4+sl5+wp8+win8+wpa81+MonoTouch+MonoAndroid/Zlib.Portable.dll"

  $ bin/pget.exe --ref net45 --repo /tmp/packages
  #r "/tmp/packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "/tmp/packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.DesignTime.dll"
  #r "/tmp/packages/Zlib.Portable.1.11.0/lib/portable-net4+sl5+wp8+win8+wpa81+MonoTouch+MonoAndroid/Zlib.Portable.dll"
#+END_SRC

Get all assembly references from a package in a repository

 - =$ pget.exe --ref [framework] --pack [package-id] --repo [repository]=

or

 - =$ pget.exe --ref [framework] --p [package-id] --repo [repository]=


#+BEGIN_SRC sh
  $ bin/pget.exe --ref net45 --pack FParsec --repo ~/nuget
  #r "/home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "/home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"

  $ bin/pget.exe --ref net45 --pack FSharp.Data --repo ~/nuget
  #r "/home/arch/nuget/FSharp.Data.2.3.1/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.dll"
  #r "/home/arch/nuget/FSharp.Data.2.3.1/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.DesignTime.dll"
#+END_SRC

*** NuGet package files nupkg files

Show a NuGet package metadata

 - =$ pget.xe --nupkg show [nupkg-file]=

#+BEGIN_SRC sh
  $ pget.exe --nupkg show ./packages/OxyPlot.Core.1.0.0/OxyPlot.Core.1.0.0.nupkg

  Id             OxyPlot.Core
  Title          OxyPlot core library (PCL)
  Tags            plotting plot charting chart
  Version        1.0.0
  Summary
  Authors        Oystein Bjorke
  Project URL    http://oxyplot.org/
  Dependencies
  Download Count -1

  Description    OxyPlot is a plotting library for .NET. This is the portable core library that is referenced by the platform-specific OxyPlot packages.

#+END_SRC

*** Show assembly metadata

 - =$ pget.exe asm --show [assembly-file]=

Example 1:

#+BEGIN_SRC sh
  $ bin/pget.exe asm --show ~/bin/nuget.exe
  Assembly Attributes
  -------------------------------------------
  Name         NuGet
  Version      3.4.4.1321
  CLR Version  v4.0.30319
  Product      NuGet
  Culture
  Company      Microsoft Corporation
  Description  NuGet Command Line
  Copyright    Microsoft Corporation. All rights reserved.
  GUID
  Com Visible  False
  Codebase     file:///home/arch/bin/nuget.exe
#+END_SRC

Example 2:

#+BEGIN_SRC sh
  $ bin/pget.exe asm --show ~/nuget/FSharp.Core.3.1.2.5/lib/net40/FSharp.Core.dll
  Assembly Attributes
  -------------------------------------------
  Name         FSharp.Core
  Version      4.3.1.0
  CLR Version  v4.0.30319
  Product      Microsoft® Visual Studio® 2013
  Culture
  Company      Microsoft Corporation
  Description  FSharp.Core.dll
  Copyright    © Microsoft Corporation. All rights reserved.
  GUID
  Com Visible  False
  Codebase     file:///home/arch/nuget/FSharp.Core.3.1.2.5/lib/net40/FSharp.Core.dll
#+END_SRC

Show assemblies referenced by an assembly file

 - =$ pget.exe asm --show-ref [assembly-file]=

#+BEGIN_SRC sh
  $ bin/pget.exe asm --show-ref ~/bin/nuget.exe
  Name = mscorlib     Version = 4.0.0.0       Culture =
  Name = Microsoft.CSharp     Version = 4.0.0.0       Culture =
  Name = System.Core      Version = 4.0.0.0       Culture =
  Name = System       Version = 4.0.0.0       Culture =
  Name = System.Xml.Linq      Version = 4.0.0.0       Culture =
  Name = System.Xml       Version = 4.0.0.0       Culture =
  Name = Microsoft.Build      Version = 4.0.0.0       Culture =
  Name = Microsoft.Build.Framework        Version = 4.0.0.0       Culture =
  Name = System.ComponentModel.Composition        Version = 4.0.0.0       Culture =
  Name = Microsoft.Build.Utilities.v4.0       Version = 4.0.0.0       Culture =
  Name = System.Numerics      Version = 4.0.0.0       Culture =
  Name = System.Data      Version = 4.0.0.0       Culture =
  Name = System.Runtime.Serialization     Version = 4.0.0.0       Culture =
  Name = System.Security      Version = 4.0.0.0       Culture =
  Name = System.ComponentModel.DataAnnotations        Version = 4.0.0.0       Culture =
  Name = WindowsBase      Version = 4.0.0.0       Culture =
  Name = System.ServiceModel      Version = 4.0.0.0       Culture =
  Name = System.Data.Services.Client      Version = 4.0.0.0       Culture =
  Name = System.IO.Compression        Version = 4.0.0.0       Culture =
  Name = System.Net.Http      Version = 4.0.0.0       Culture =
  Name = System.IdentityModel     Version = 4.0.0.0       Culture =
  Name = System.Net.Http.WebRequest       Version = 4.0.0.0       Culture =
#+END_SRC

*** Generate GUID

 - =$ pget.exe --guid=

#+BEGIN_SRC sh
  $ bin/pget.exe --guid
  c4969f50-7a17-4f8f-ac9d-d783a9a8f8d4
#+END_SRC

* Pget.dll

Pget.dll is a F# library that provides a high level interface and
functional wrappers to NuGet.Core API.

* Repository

 - https://www.github.com/caiorss/pget
