#+TITLE: Pget .NET Command Line toolbox and Interface for NuGet.Core and F#
#+AUTHOR: Caio Rodrigues
#+EMAIL:  caiorss [DOT] rodrigues [DOT] gmail [DOT] com
#+DESCRIPTION: F# Command line interface to NuGet API.
#+KEYWORDS: NuGet F# fsharp csharp .net dotnet tool cli command line toolbox cross-platform

#+STARTUP: content
#+LANGUAGE: en
#+OPTIONS:   H:4

#+INFOJS_OPT: view:info toc:t ltoc:t ftoc:nil mouse:underline button:nil path:theme/org-info.js
#+HTML_HEAD: <link href="theme/style.css" rel="stylesheet"> 

* Pget.exe - Package Get
** Overview

Pget.exe is high level wrapper to NuGet.core package which provides
command line tools to manage dependencies in F# projects or .NET projects.

Objective: Provide NuGet.Core integration with external tools, text editors
like Emacs and VIM and also command line integration with NuGet API. 


*WHY pget ?* 

I create pget because existing command line tools doesn't have all
functionality provided by Visual Studio and Package Manager Console
like display package metadata, search packages in NuGet repository,
display packages' metadata from local repository or project repository
./packages and show Nuget package file metadata and files.


*Feature*

 - Search  packages in Nuget repository


 - Install NuGet packages


 - Display all assembly references in a repository


 - Generate assembly references from all repository or single package
   for F# scripts. 


 - Show packages' metadata like description, summary, web site and so on.


 - Inspect .NET assemblies.
   - Show .NET assemblies metadata
   - Show .NET referenced assemblies
   - Show assembly resources
   - Show namespaces in assembly
   - Show classes in assembly
   - Show class methods 

 - Show NuGet packages *.nupkg file metadata.


 - Get packages' assembly references from local repository and project
   repository (./packages) for F# scripts.

*Repository:*

 -  https://www.github.com/caiorss/pget

** Get binary release

The binary releases are published to orphan-branch [[https://github.com/caiorss/pget/tree/build][build]]. 

*Manual download*

 - [[https://github.com/caiorss/pget/raw/build/pget.exe][Download pget.exe]]

*Automatic Download* 

#+BEGIN_SRC sh 
  ~/Downloads $ curl -O -L https://github.com/caiorss/pget/raw/build/pget.exe
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   127  100   127    0     0    169      0 --:--:-- --:--:-- --:--:--   169
  100 2143k  100 2143k    0     0   257k      0  0:00:08  0:00:08 --:--:--  529k
  ~/Downloads $


  ~/Downloads $ /usr/bin/chmod +x pget.exe

  ~/Downloads $ ./pget.exe -v 

      Pget - Package Get - Version 1.0 
      Copyright (C) 2016 Caio Rodrigues        
#+END_SRC

or 

#+BEGIN_SRC sh 
  cd ~/bin 
  curl -O -L https://github.com/caiorss/pget/raw/build/pget.exe
  /usr/bin/chmod +x pget.exe
  ./pget.exe -v 
#+END_SRC

** Build instructions
*** Build with Makefile

Run the command =$ make exe=. It assumes that fsc - the F# compiler
and nuget.exe are in the $PATH variable. It builds the standlone app
pget.exe with all dependencies static linked and also FSharp.Core (F#
runtime) static linked.

#+BEGIN_SRC sh
  $ make exe
  fsc src/Pget.fs src/PgetCmd.fsx --out:bin/pget.exe \
  --target:exe \
      --platform:anycpu \
      -r:packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll \
  -r:packages/Microsoft.Web.Xdt.2.1.1/lib/net40/Microsoft.Web.XmlTransform.dll \
  --staticlink:NuGet.Core \
  --standalone
  F# Compiler for F# 4.1
  Freely distributed under the Apache 2.0 Open Source License

#+END_SRC

Testing:

#+BEGIN_SRC sh
  $ file bin/pget.exe
  bin/pget.exe: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows

  $ bin/pget.exe --version

   Pget - Package Get - Version 1.3.1 
   2016 Public Domain Software
   Repository - https://github.com/caiorss/pget
      
#+END_SRC

*** Build with Xbuild or Msbuild

Msbuild 

- =$ msbuild pget-exe.fsproj /p:Configuration=Release=

Xbuild 

 - =$ xbuild pget-exe.fsproj /p:Configuration=Release=

#+BEGIN_SRC sh
$ cd obj/Release && ./Pget.exe -v

 Pget - Package Get - Version 1.3.1 
 2016 Public Domain Software
 Repository - https://github.com/caiorss/pget
#+END_SRC

** Commands
*** Print Version

 - =$ pget.exe --version= or =$ pget.exe -v=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe -v

   Pget - Package Get - Version 1.3.1 
   2016 Public Domain Software
   Repository - https://github.com/caiorss/pge
#+END_SRC
*** Print help

 - =$ pget.exe=

Example:

#+BEGIN_SRC text
  $ bin/pget.exe 
  Pget - Package Get - Enhanced command line interface to NuGet.Core

    pget.exe repo                                Show help for repo commands
    pget.exe nuget                               Show help for nuget related commands                           
    pget.exe asm                                 Show help for assembly related commands.
    pget.exe nupkg                               Show help for Nuget packages related commands.                          
                            

    List Repository

      repo --list                                 List all packages in current repository ./package
      repo [path] --list                          List all package in [path] repository.

    Show repository 
   
      repo --show                                 Show all packages in current ./packages repository
      repo [path] --show                          Show all packages in [path] repository.
    
    Show package metadata

      repo --show  [pack]                         Show the package [pack] in ./packages directory
      repo [path] --show [pack]                   Show the package [pack] in [repo] directory.

    Show package files 

      repo --files [pack]                    Show content files of package [pack] in ./packages
      repo [path] --files [pack]             Show content files of package [pack] in [repo]

    Install package to repository  

      repo --install [pack]                       Install the latest version of package [pack] to ./packages
      repo --install [pack] [ver]                 Install the version [ver] of package [pack]
      repo [path] --install [pack]                Install the latest version of package [pack] to a repository [path] i.e: ~/nuget
      repo [path] --install [pack] [ver]          Install the version [ver] of package [pack] to a repository [path]


    Install a list of packages passed as argument
      repo --install-list FParsec NuGet.Core-2.0.0               Install those packages to ./packages
      repo /tmp/repo --install-list FParsec NuGet.Core-2.0.0     Install those packages to /tmp/repository

    Install a list of packages listed in a file

      repo --install-from-file                    Install all packages listed in the file ./packages.list to ./packages directory.
      repo --install-from-file [file]             Install all packages listed in the file ./packages.list to ./packages directory.
      repo [path] --install-from-file [file]      Install all packages listed in the file [file] to [path]


    Open package project URL or Licence URL

      repo --url [pack]                           Browse project URL of a package [pack] in ./packages.
      repo --license [pack]                       Browse licence URL of a package [pack] in ./packages.
      repo [path] --url [pack]                    Browse project URL of a package [pack] in [path]
      repo [path] --license [pack]                Browse licence URL of a package [pack] in [path]

    Show references for F# *.fsx scripts:        [frm]:  .NET Framework  net40 | net45   

      repo --ref [frm]                            Show all assembly references from current ./packages.
      repo --ref  --pack [pack]                   Show all assembly references from a package [pack] at ./packages.              
      repo [path] --ref [frm]                     Show all assembly references from current [repo] directory.
      repo [path] --ref [frm] [pack]              Show all assembly references from a package at [repo] directory        
          

    Nuget commands:

      nuget --search [package]                    Search a package by name.  
      nuget --show   [package]                    Show package information (metadata).
      nuget --open                                Open NuGet web site - https://www.nuget.org       
          

    Nupkg Files:

      nupkg --show  [file]                        Show metadata of a *.nupkg file
      nupkg --files [file]                        Show files in nupkg [file]        
          

    Assembly files: *.exe or *.dll

      asm --info [file]                                    Show all assembly attributes from an assembly [file].
      asm --refs [file]                                    Show all assembly references from an assembly [file].
      asm --resources  [file]                              Show resources from an assembly file.
      asm --namespace|-ns [file]                           Show all exported namespaces.
      asm --namespace|-ns [file] [nspace]                  Show all types within an exported namespace from an assembly [file].

      asm --type [file]                                    Show all types exported by assembly [file]
      asm --type [file] [type]                             Show information about [type] exported by assembly [file].
      asm --interface [file]                               Show all interfaces exported by assembly [file]. 
      asm --abstract  [file]                               Show all abstract classes exported by assembly [file].
     
      asm --class  [file]                                  Show all classes exported by assembly [file].
      asm --classn [file]                                  Show all non-abstract classes exported by assembly [file]
          

    Fsproj - Helpers for fsproj files.

      fsproj --ref [frm]                           Generate include references tags from all packages in ./packages    
                              

    Show system information

      --system 

    Generate Guid - Globally Unique Identifier 

      --guid 

    --------------------------------------------

    Command abbreviations:

      --install            -i
      --install-from-file  -if
      --install-list       -il
      --help               -h
      --version            -v
      --ver                -v
      --list               -l
      --search             -s
      --show               -sh
           

   Pget - Package Get - Version 1.5.0.0 
   2016 Public Domain Software
   Repository - https://github.com/caiorss/pget
#+END_SRC

*** Local Repository
**** List packages
***** List packages in project repository ./packages directory:

 - =$ pget.exe repo --list= or =$ pget.exe -l=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo -l
  Microsoft.Web.Xdt 2.1.1
  NuGet.Core 2.12.0


  $ tree packages
  packages
  ├── Microsoft.Web.Xdt.2.1.1
  │   ├── lib
  │   │   └── net40
  │   │       └── Microsoft.Web.XmlTransform.dll
  │   └── Microsoft.Web.Xdt.2.1.1.nupkg
  └── NuGet.Core.2.12.0
      ├── lib
      │   └── net40-Client
      │       └── NuGet.Core.dll
      └── NuGet.Core.2.12.0.nupkg

  6 directories, 4 files
#+END_SRC

***** List packages in a local repository

 - =$ pget.exe repo --list [directory]= or =$ pget.exe --l [directory]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo -l /home/arch/nuget
  Common.Logging 2.1.2
  Deedle 1.2.5
  Deedle.RPlugin 1.2.5
  DynamicInterop 0.7.4
  EntityFramework 6.0.0
  Eto.Forms 2.2.0
  Eto.Platform.Gtk 2.2.0
  Eto.Platform.Gtk3 2.2.0
  FAKE 4.39.0
  ...
#+END_SRC
**** Show package information (metadata)
***** Show all packages in project repository (./packages)

 - =$ pget.exe pget repo --show= or =$ pget.exe repo -sh=

Example:

#+BEGIN_SRC txt
  $ bin/pget.exe repo --show

  Id             Microsoft.Web.Xdt
  Title          Microsoft Xml Document Transformation
  Tags
  Version        2.1.1
  Summary        Microsoft Xml Document Transformation (XDT) enables transformig XML files. This is the same technology used to transform web.config files for Visual Studio web projects.
  Authors        Microsoft Corporation
  Project URL
  Dependencies
  Download Count -1

  Description    Microsoft Xml Document Transformation (XDT) library. For more info on XDT please visit http://msdn.microsoft.com/en-us/library/dd465326.aspx.


  Id             NuGet.Core
  Title
  Tags            nuget
  Version        2.12.0
  Summary
  Authors        Outercurve Foundation
  Project URL    https://github.com/NuGet/NuGet2
  Dependencies   Microsoft.Web.Xdt 2.1.0
  Download Count -1

  Description    NuGet.Core is the core framework assembly for NuGet that the rest of NuGet builds upon.

#+END_SRC

***** Show all packages in a local repository

 - =$ pget.exe repo [path] --show= or =$ pget.exe repo [path] -sh=

Example:

#+BEGIN_SRC txt
  $ bin/pget.exe repo /tmp/testrepo --show

  Id             FParsec
  Title          FParsec
  Tags            parser combinator f# fsharp c# csharp parsec fparsec 
  Version        1.0.2
  Summary        
  Authors        Stephan Tolksdorf
  Project URL    http://www.quanttec.com/fparsec/
  Dependencies   
  Download Count -1

  Description    FParsec is a parser combinator library for F#.

  You can find comprehensive documentation for FParsec at http://www.quanttec.com/fparsec. The documentation includes a feature list, a tutorial, a user’s guide and an API reference.

  This package uses the basic “low-trust” configuration of FParsec, which does not use any unverifiable code and is optimized for maximum portability. If you need to parse very large files or if you employ FParsec for performance-critical jobs, consider using the alternate “Big Data Edition” NuGet package (see nuget.org/packages/fparsec-big-data-edition).
                            

  Id             FSharp.Data
  Title          F# Data
  Tags            F# fsharp data typeprovider WorldBank CSV HTML CSS JSON XML HTTP linqpad-samples 
  Version        2.3.2
  Summary        Library of F# type providers and data access tools
  Authors        Tomas Petricek,  Gustavo Guerra,  Colin Bull
  Project URL    http://fsharp.github.io/FSharp.Data
  Dependencies   Zlib.Portable 1.11.0, Zlib.Portable 1.11.0, Zlib.Portable 1.11.0
  Download Count -1

  Description    The F# Data library (FSharp.Data.dll) implements everything you need to access data in your F# applications and scripts. It implements F# type providers for working with structured file formats (CSV, HTML, JSON and XML) and for accessing the WorldBank data. It also includes helpers for parsing CSV, HTML and JSON files and for sending HTTP requests.
                            
  ...
#+END_SRC

***** Show a single package in project repository (./packages)

 - =$ pget.exe repo --show [package-Id]= or - =$ pget.exe repo -sh [package-Id]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo --show NuGet.Core

  Id             NuGet.Core
  Title
  Tags            nuget
  Version        2.12.0
  Summary
  Authors        Outercurve Foundation
  Project URL    https://github.com/NuGet/NuGet2
  Dependencies   Microsoft.Web.Xdt 2.1.0
  Download Count -1

  Description    NuGet.Core is the core framework assembly for NuGet that the rest of NuGet builds upon.
#+END_SRC

***** Show a single package in a Local Repository

 - =$ pget.exe repo [path] --show [package-Id]=

or

 - =$ pget.exe repo [path] -sh [package-Id]=

Example:

#+BEGIN_SRC txt
  $ bin/pget.exe repo ~/nuget --show NUnit.Console

  Id             NUnit.Console
  Title          NUnit Console Runner Version 3 Plus Extensions
  Tags            nunit test testing tdd runner
  Version        3.5.0
  Summary        Console runner for the NUnit 3 unit-testing framework with selected extensions.
  Authors        Charlie Poole
  Project URL    http://nunit.org/
  Dependencies   NUnit.ConsoleRunner 3.5.0, NUnit.Extension.NUnitProjectLoader 3.5.0, NUnit.Extension.VSProjectLoader 3.5.0, NUnit.Extension.NUnitV2ResultWriter 3.5.0, NUnit.Extension.NUnitV2Driver 3.5.0, NUnit.Extension.TeamCityEventListener 1.0.2
  Download Count -1

  Description    This package includes the nunit3-console runner and test engine for version 3.0 of the NUnit unit-testing framework.

        The following extensions are included with this package:
        ,* NUnitProjectLoader     - loads tests from NUnit projects
        ,* VSProjectLoader        - loads tests from Visual Studio projects
        ,* NUnitV2ResultWriter    - saves results in NUnit V2 format.
        ,* NUnitV2FrameworkDriver - runs NUnit V2 tests.
        ,* TeamCityEventListener - supports special progress messages used by teamcity.

        Other extensions, if needed, must be installed separately
#+END_SRC
**** Show package files
***** Show files of a package in project repository ./packages

 - =$ pget.exe repo --files [package-id]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo --files OxyPlot.Core

  packages/OxyPlot.Core.1.0.0/lib/portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1+Xamarin.iOS10/OxyPlot.dll
  packages/OxyPlot.Core.1.0.0/lib/portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1+Xamarin.iOS10/OxyPlot.pdb
  packages/OxyPlot.Core.1.0.0/lib/portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1+Xamarin.iOS10/OxyPlot.xml
  packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.dll
  packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.pdb
  packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.xml
  packages/OxyPlot.Core.1.0.0/lib/net40-client/OxyPlot.dll
  packages/OxyPlot.Core.1.0.0/lib/net40-client/OxyPlot.pdb
  packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.dll
  packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.pdb
  packages/OxyPlot.Core.1.0.0/lib/sl5/OxyPlot.dll
  packages/OxyPlot.Core.1.0.0/lib/sl5/OxyPlot.pdb
  packages/OxyPlot.Core.1.0.0/README.md
  packages/OxyPlot.Core.1.0.0/CHANGELOG.md


  $ bin/pget.exe repo --files FParsec
  packages/FParsec.1.0.2/lib/net40-client/FParsec.dll
  packages/FParsec.1.0.2/lib/net40-client/FParsec.XML
  packages/FParsec.1.0.2/lib/net40-client/FParsecCS.dll
  packages/FParsec.1.0.2/lib/net40-client/FParsecCS.XML
  packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll
  packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.XML
  packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll
  packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.XML
#+END_SRC

***** Show files of a package in a local repository  

 - =$ pget.exe repo [path] --files [package-id]=

#+BEGIN_SRC sh
  $ bin/pget.exe repo ~/nuget --files FParsec

  /home/arch/nuget/FParsec.1.0.2/lib/net40-client/FParsec.dll
  /home/arch/nuget/FParsec.1.0.2/lib/net40-client/FParsec.XML
  /home/arch/nuget/FParsec.1.0.2/lib/net40-client/FParsecCS.dll
  /home/arch/nuget/FParsec.1.0.2/lib/net40-client/FParsecCS.XML
  /home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll
  /home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.XML
  /home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll
  /home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.XML


  $ bin/pget.exe repo ~/nuget --files Mono.Cecil

  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net20/Mono.Cecil.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net20/Mono.Cecil.Mdb.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net20/Mono.Cecil.Pdb.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net35/Mono.Cecil.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net35/Mono.Cecil.Mdb.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net35/Mono.Cecil.Pdb.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net35/Mono.Cecil.Rocks.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net40/Mono.Cecil.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net40/Mono.Cecil.Mdb.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net40/Mono.Cecil.Pdb.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/net40/Mono.Cecil.Rocks.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/sl40/Mono.Cecil.dll
  /home/arch/nuget/Mono.Cecil.0.9.5.4/lib/sl40/Mono.Cecil.Rocks.dll

#+END_SRC
**** Get assembly references for F# scripts
***** Get all assembly references from current ./packages repository.

 - =$ pget.exe repo --ref [framework]=

The framework is the .NET framework version. It can be:

 - net40 for .NET 4.0
 - net45 for .NET 4.5

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo --ref net40
  #r "packages/FParsec.1.0.2/lib/net40-client/FParsec.dll"
  #r "packages/FParsec.1.0.2/lib/net40-client/FParsecCS.dll"
  #r "packages/Microsoft.Web.Xdt.2.1.1/lib/net40/Microsoft.Web.XmlTransform.dll"
  #r "packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll"
  #r "packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.dll"
  #r "packages/OxyPlot.Pdf.1.0.0/lib/net40/OxyPlot.Pdf.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.DocumentObjectModel.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.Rendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.RtfRendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.Charting.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.DocumentObjectModel.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.Rendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.RtfRendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.Charting.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.resources.dll"


  $ bin/pget.exe repo --ref net45
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"
  #r "packages/Microsoft.Web.Xdt.2.1.1/lib/net40/Microsoft.Web.XmlTransform.dll"
  #r "packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll"
  #r "packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.dll"
  #r "packages/OxyPlot.Pdf.1.0.0/lib/net40/OxyPlot.Pdf.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.DocumentObjectModel.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.Rendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/MigraDoc.RtfRendering.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.Charting.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/PdfSharp.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.DocumentObjectModel.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.Rendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/MigraDoc.RtfRendering.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.Charting.resources.dll"
  #r "packages/PDFsharp-MigraDoc-GDI.1.32.4334.0/lib/net20/de/PdfSharp.resources.dll"

#+END_SRC

***** Get all assembly references from a package in ./packages:

 - =$ pget.exe repo --ref [framework] [package-id]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo --ref net45 FParsec
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"
#+END_SRC

***** Get all assembly references from a local repository.

 - =$ pget.exe repo [path] --ref [framework]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo /tmp/packages -i FSharp.Data 
  Installing: FSharp.Data 2.3.2

  $ bin/pget.exe repo /tmp/packages -i FParsec
  Installing: FParsec 1.0.2


  $ ls /tmp/packages/
  FParsec.1.0.2/  FSharp.Data.2.3.2/  Zlib.Portable.1.11.0/

  $ bin/pget.exe repo /tmp/packages --ref net40
  #r "/tmp/packages/FParsec.1.0.2/lib/net40-client/FParsec.dll"
  #r "/tmp/packages/FParsec.1.0.2/lib/net40-client/FParsecCS.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/net40/FSharp.Data.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/net40/FSharp.Data.DesignTime.dll"
  #r "/tmp/packages/Zlib.Portable.1.11.0/lib/portable-net4+sl5+wp8+win8+wpa81+MonoTouch+MonoAndroid/Zlib.Portable.dll"

  $ bin/pget.exe repo /tmp/packages --ref net45
  #r "/tmp/packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "/tmp/packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.dll"
  #r "/tmp/packages/FSharp.Data.2.3.2/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.DesignTime.dll"
  #r "/tmp/packages/Zlib.Portable.1.11.0/lib/portable-net4+sl5+wp8+win8+wpa81+MonoTouch+MonoAndroid/Zlib.Portable.dll"
#+END_SRC

***** Get all assembly references from a package in a local repository

 - =$ pget.exe repo [path --ref [framework] [package-id]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo ~/nuget --ref net45 FParsec
  #r "/home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll"
  #r "/home/arch/nuget/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll"

  $ bin/pget.exe repo ~/nuget --ref net45 FSharp.Data
  #r "/home/arch/nuget/FSharp.Data.2.3.1/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.dll"
  #r "/home/arch/nuget/FSharp.Data.2.3.1/lib/portable-net45+netcore45+wpa81+wp8/FSharp.Data.DesignTime.dll"
#+END_SRC
**** Open package project URL in the browser 
***** Open project URL of package in ./packages

 - =$ pget.exe repo --url [packageId]= 

Example: 

#+BEGIN_SRC sh
$ bin/pget.exe repo --url FParsec
Opening http://www.quanttec.com/fparsec/
#+END_SRC

***** Open project URL of package in a local repository

 - =$ pget.exe repo [path] --url [packageId]= 

Example: 

#+BEGIN_SRC sh
$ bin/pget.exe repo ~/nuget --url Eto.Forms
Opening https://github.com/picoe/Eto
#+END_SRC

**** Open package licensee URL in the browser
***** Open license URL of package in ./packages

 - =$ pget.exe repo --license [packageId]= 

Example: 

#+BEGIN_SRC sh
$ bin/pget.exe repo --license FParsec
Opening http://www.quanttec.com/fparsec/license.html
#+END_SRC

***** Open license URL of package in a local repository

 - =$ pget.exe repo [path]  --licence [packageId]=

Example:

#+BEGIN_SRC sh
$ bin/pget.exe repo ~/nuget --license NUnit.Console
Opening http://nunit.org/nuget/nunit3-license.txt
#+END_SRC

**** Install packages
***** Install the lastest version of a package to ./packages (Project repository)

 - =$ pget.exe repo --install [package-id]= or - =$ pget.exe repo -i [package-id]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo --install OxyPlot.Pdf
  Installing: OxyPlot.Pdf 1.0.0

  $ ls -l packages
  total 0
  drwxrwxrwx 1 arch arch 280 dez 19 00:52 Microsoft.Web.Xdt.2.1.1/
  drwxrwxrwx 1 arch arch 264 dez 19 01:45 NuGet.Core.2.12.0/
  drwxrwxrwx 1 arch arch 488 dez 19 02:22 OxyPlot.Core.1.0.0/
  drwxrwxrwx 1 arch arch 480 dez 19 02:22 OxyPlot.Pdf.1.0.0/
  drwxrwxrwx 1 arch arch 296 dez 19 02:22 PDFsharp-MigraDoc-GDI.1.32.4334.0/

   bin/pget.exe repo -sh OxyPlot.Core

  Id             OxyPlot.Core
  Title          OxyPlot core library (PCL)
  Tags            plotting plot charting chart
  Version        1.0.0
  Summary
  Authors        Oystein Bjorke
  Project URL    http://oxyplot.org/
  Dependencies
  Download Count -1

  Description    OxyPlot is a plotting library for .NET. This is the portable core library that is referenced by the platform-specific OxyPlot packages.

#+END_SRC

***** Install a specific version of package  to ./packages

 - =$ pget.exe repo --install [package-id] [version]=

or

 - =$ pget.exe repo -i [package-id] [version]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo -i FParsec 1.0.2

  $ ls -l packages
  total 0
  drwxrwxrwx 1 arch arch 256 dez 19 02:31 FParsec.1.0.2/
  drwxrwxrwx 1 arch arch 280 dez 19 00:52 Microsoft.Web.Xdt.2.1.1/
  drwxrwxrwx 1 arch arch 264 dez 19 01:45 NuGet.Core.2.12.0/
  drwxrwxrwx 1 arch arch 488 dez 19 02:22 OxyPlot.Core.1.0.0/
  drwxrwxrwx 1 arch arch 480 dez 19 02:22 OxyPlot.Pdf.1.0.0/
  drwxrwxrwx 1 arch arch 296 dez 19 02:22 PDFsharp-MigraDoc-GDI.1.32.4334.0/
#+END_SRC

***** Install the lastest version of a package to a local repository

 - =$ pget.exe repo [path] --install [package-id]=

or

 - =$ pget.exe repo [path] -i [package-id] -r [path]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo -i /home/arch/nuget  OxyPlot.Pdf 
  Installing: OxyPlot.Pdf 1.0.0

  $ bin/pget.exe repo /home/arch/nuget -sh OxyPlot.Pdf

  Id             OxyPlot.Pdf
  Title          OxyPlot PDF extensions (for Silverlight and NET4)
  Tags            pdf plotting plot charting chart
  Version        1.0.0
  Summary
  Authors        Oystein Bjorke
  Project URL    http://oxyplot.org/
  Dependencies   OxyPlot.Core [1.0.0], PDFsharp-MigraDoc-GDI [1.32.4334], OxyPlot.Core [1.0.0], PDFsharp-MigraDoc-GDI [1.32.4334], OxyPlot.Core [1.0.0]
  Download Count -1

  Description    OxyPlot is a plotting library for .NET. This package contains .pdf export extensions for .NET 4 (based on PDFsharp) and Silverlight (based on SilverPDF).

#+END_SRC

***** Install a specific version of package to a local repository

 - =$ pget.exe repo [path] --install [package-id] [version]=

or

 - =$ pget.exe repo [path] -i [package-id] -v [package]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe repo ~/nuget -i Microsoft.Web.Xdt 1.0.0
#+END_SRC
**** Install a list of packages 
***** Install a list of packages to ./packages 

 - =$ pget.exe repo --install-list FParsec-1.0.2 OxyPlot= 

or

- =$ pget.exe repo -il FParsec-1.0.2 OxyPlot= 

If the version is not specified it installs the lastest version.

***** Install a list of pacakges to a local repository 

 - =$ pget.exe repo ~/nuget --install-list FParsec-1.0.2 OxyPlot= 

or

 - =$ pget.exe repo ~/nuget -il FParsec-1.0.2 OxyPlot ... packageN= 

**** Install packages listed in a file
****** Install all packages listed in the file ./packages.list to ./packages

 - =$ pget.exe repo --install-from-file=

or

 - =$ pget.exe repo -if=

Example of the file packages.list. If the version is not listed, it
installs the latest version of the packages to ./packages.

File: packages.list

#+BEGIN_SRC sh
  FSharp.Data              1.0.0
  Deedle                   1.0.0
  OxyPlot.Pdf
  OxyPlot.WindowsForms
#+END_SRC

****** Install all packages listed in the file ./packages.list to ./packages

 - =$ pget.exe repo --install-from-file [packages-list-file]=

or

 - =$ pget.exe repo -if [package-list-file]=
*** NuGet Repository 
**** Search a package

 - =$ pget.exe nuget --search [keyword]= or - =$ pget.exe nuget -s [keywork]=

Example:

#+BEGIN_SRC txt
  $ bin/pget.exe nuget -s oxyplot

  Id             AnnotationGUIOxyplot
  Title
  Tags
  Version        0.0.1
  Summary
  Authors        tschwarz
  Project URL
  Dependencies
  Download Count 68

  Description    My package description.


  Id             Eto.OxyPlot
  Title          Eto.OxyPlot
  Tags
  Version        1.2.0-beta
  Summary
  Authors        Loren Van Spronsen
  Project URL
  Dependencies   Eto.Forms 2.2.0, OxyPlot.Core 1.0.0-unstable2063
  Download Count 3382

  Description    OxyPlot bindings for the Eto UI framework

 ... ... ...
#+END_SRC

**** Display package information (metadata)

 - =pget.exe nuget --show=

Example:

#+BEGIN_SRC txt
  $ bin/pget.exe nuget --show FParsec

  Id             FParsec
  Title          FParsec
  Tags            parser combinator parsec fsharp 
  Version        0.9.1
  Summary        FParsec is a parser combinator library for F#.
  Authors        Stephan Tolksdorf (FParsec),   Ryan Riley (NuGet Package)
  Project URL    http://quanttec.com/fparsec/
  Dependencies   
  Download Count 66877

  Description    FParsec is a parser combinator library for F#


  $ bin/pget.exe nuget --show FParsecsdadfsf
  Error: I can't find the package FParsecsdadfsf

  $ bin/pget.exe nuget --show FSharp.Core

  Id             FSharp.Core
  Title          FSharp.Core
  Tags           f#
  Version        2.0.0.0
  Summary        FSharp.Core.dll
  Authors        Microsoft
  Project URL    
  Dependencies   
  Download Count 460728

  Description    FSharp.Core.dll which can be referenced in other nuget packages.

#+END_SRC

*** NuGet package files nupkg files
**** Show package file metadata

Show a NuGet package metadata

 - =$ pget.xe nupkg --show [nupkg-file]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe nupkg --show ./packages/FParsec.1.0.2/FParsec.1.0.2.nupkg

  Id             FParsec
  Title          FParsec
  Tags            parser combinator f# fsharp c# csharp parsec fparsec 
  Version        1.0.2
  Summary        
  Authors        Stephan Tolksdorf
  Project URL    http://www.quanttec.com/fparsec/
  Dependencies   
  Download Count -1

  Description    FParsec is a parser combinator library for F#.

  You can find comprehensive documentation for FParsec at http://www.quanttec.com/fparsec. The documentation includes a feature list, a tutorial, a user’s guide and an API reference.

  This package uses the basic “low-trust” configuration of FParsec, which does not use any unverifiable code and is optimized for maximum portability. If you need to parse very large files or if you employ FParsec for performance-critical jobs, consider using the alternate “Big Data Edition” NuGet package (see nuget.org/packages/fparsec-big-data-edition).
    
#+END_SRC

**** Show package files 

 - =$ pget.exe nupkg --files [nupkg-file]=

Example:

#+BEGIN_SRC sh 
  $ bin/pget.exe nupkg --files ./packages/FParsec.1.0.2/FParsec.1.0.2.nupkg
  lib/net40-client/FParsec.dll
  lib/net40-client/FParsec.XML
  lib/net40-client/FParsecCS.dll
  lib/net40-client/FParsecCS.XML
  lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll
  lib/portable-net45+netcore45+wpa81+wp8/FParsec.XML
  lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll
  lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.XML
#+END_SRC

*** Fsproj Helpers

Generate include tags for all packages in project repository (./packages)

- =$ pget.exe fsproj --ref [framework]=

Where framework can be

 - net40 for .NET 4.0
 - net45 for .NET 4.5

#+BEGIN_SRC sh
  $ bin/pget.exe fsproj --ref net45
  <Reference Include="FParsec">
       <HintPath>packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsec.dll</HintPath>
  </Reference>
  <Reference Include="FParsecCS">
       <HintPath>packages/FParsec.1.0.2/lib/portable-net45+netcore45+wpa81+wp8/FParsecCS.dll</HintPath>
  </Reference>
  <Reference Include="FS.INIReader">
       <HintPath>packages/FS.INIReader.1.0.3/lib/net45/FS.INIReader.dll</HintPath>
  </Reference>
  <Reference Include="Microsoft.Web.XmlTransform">
       <HintPath>packages/Microsoft.Web.Xdt.2.1.1/lib/net40/Microsoft.Web.XmlTransform.dll</HintPath>
  </Reference>
  <Reference Include="NuGet.Core">
       <HintPath>packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll</HintPath>
  </Reference>
  <Reference Include="OxyPlot">
       <HintPath>packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.dll</HintPath>
  </Reference>
  <Reference Include="OxyPlot.Pdf">
       <HintPath>packages/OxyPlot.Pdf.1.0.0/lib/net40/OxyPlot.Pdf.dll</HintPath>
  </Reference>
  ...
#+END_SRC

*** Assembly metadata
**** Show Assembly Attributes

 - =$ pget.exe asm --info [assembly-file]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe asm --info ~/bin/nuget.exe
  Assembly Attributes
  -------------------------------------------
  Name         NuGet
  Version      3.4.4.1321
  CLR Version  v4.0.30319
  Product      NuGet
  Culture
  Company      Microsoft Corporation
  Description  NuGet Command Line
  Copyright    Microsoft Corporation. All rights reserved.
  GUID
  Com Visible  False
  Codebase     file:///home/arch/bin/nuget.exe
#+END_SRC

Example 2:

#+BEGIN_SRC sh
  $ bin/pget.exe asm --info ~/nuget/FSharp.Core.3.1.2.5/lib/net40/FSharp.Core.dll
  Assembly Attributes
  -------------------------------------------
  Name         FSharp.Core
  Version      4.3.1.0
  CLR Version  v4.0.30319
  Product      Microsoft® Visual Studio® 2013
  Culture
  Company      Microsoft Corporation
  Description  FSharp.Core.dll
  Copyright    © Microsoft Corporation. All rights reserved.
  GUID
  Com Visible  False
  Codebase     file:///home/arch/nuget/FSharp.Core.3.1.2.5/lib/net40/FSharp.Core.dll
#+END_SRC

**** Show assembly references

Show assemblies referenced by an assembly file

 - =$ pget.exe asm --refs [assembly-file]=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe asm --refs ~/bin/nuget.exe
  Name = mscorlib     Version = 4.0.0.0       Culture =
  Name = Microsoft.CSharp     Version = 4.0.0.0       Culture =
  Name = System.Core      Version = 4.0.0.0       Culture =
  Name = System       Version = 4.0.0.0       Culture =
  Name = System.Xml.Linq      Version = 4.0.0.0       Culture =
  Name = System.Xml       Version = 4.0.0.0       Culture =
  Name = Microsoft.Build      Version = 4.0.0.0       Culture =
  Name = Microsoft.Build.Framework        Version = 4.0.0.0       Culture =
  Name = System.ComponentModel.Composition        Version = 4.0.0.0       Culture =
  Name = Microsoft.Build.Utilities.v4.0       Version = 4.0.0.0       Culture =
  Name = System.Numerics      Version = 4.0.0.0       Culture =
  Name = System.Data      Version = 4.0.0.0       Culture =
  Name = System.Runtime.Serialization     Version = 4.0.0.0       Culture =
  Name = System.Security      Version = 4.0.0.0       Culture =
  Name = System.ComponentModel.DataAnnotations        Version = 4.0.0.0       Culture =
  Name = WindowsBase      Version = 4.0.0.0       Culture =
  Name = System.ServiceModel      Version = 4.0.0.0       Culture =
  Name = System.Data.Services.Client      Version = 4.0.0.0       Culture =
  Name = System.IO.Compression        Version = 4.0.0.0       Culture =
  Name = System.Net.Http      Version = 4.0.0.0       Culture =
  Name = System.IdentityModel     Version = 4.0.0.0       Culture =
  Name = System.Net.Http.WebRequest       Version = 4.0.0.0       Culture =
#+END_SRC

**** Show Assembly Resources 

 - =$ pget.exe asm --resources [asmfile]= 

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe asm --resources bin/pget.exe 
  FSCore.resources
  NuGet.CommonResources.resources
  NuGet.NuGet.Frameworks.Strings.resources
  NuGet.Resources.AnalysisResources.resources
  NuGet.Resources.NuGetResources.resources
  NuGet.Authoring.nuspec.xsd
#+END_SRC

**** Show all exported types 

 - =$ pget.exe asm --type [asmFile]= 

Example: 

#+BEGIN_SRC sh
$ bin/pget.exe repo --files NuGet.Core
packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll

$ bin/pget.exe asm --type packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll
NuGet.IPackageRule
NuGet.PackageIssue
NuGet.DefaultPackageRuleSet
NuGet.PackageIssueLevel
NuGet.AssemblyMetadata
NuGet.AssemblyMetadataExtractor
NuGet.IFrameworkTargetable
NuGet.IPackageFile

...

NuGet.IPackageAssemblyReference
NuGet.PhysicalPackageAssemblyReference
NuGet.ConfigurationDefaults
NuGet.ICredentialProvider
NuGet.SettingsCredentialProvider
NuGet.ISettings
NuGet.NullSettings
NuGet.Settings
NuGet.SettingValue

...

NuGet.Resources.NuGetResources
NuGet.ProjectSystemExtensions
NuGet.PathUtility
NuGet.CryptoHashProvider
NuGet.StreamExtensions
NuGet.PackageHelper
NuGet.XmlUtility
NuGet.IProjectSystem
NuGet.PackageSaveModes
NuGet.Constants
NuGet.PackageDependency
NuGet.VersionUtility
NuGet.XElementExtensions
#+END_SRC

**** Show type information 

 - =$ pget.exe asm --type [asmFile] [TypeName]=

#+BEGIN_SRC text
$ bin/pget.exe repo --files NuGet.Core
packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll

$ bin/pget.exe asm --type packages/NuGet.Core.2.12.0/lib/net40-Client/NuGet.Core.dll NuGet.ZipPackage

Type Info:

  Name:           ZipPackage
  Full Name:      NuGet.ZipPackage
  Namespace:      NuGet
  Module:         NuGet.Core.dll
  Base Type:      NuGet.LocalPackage

Predicates

  Class:          True
  Abstract Class: False
  Primitive       False
  Array:          False
  Interface       False   
  Enum            False
  Public          True
  Visible         True
  
                        

Fields
----------------

Properties
----------------
	System.String Id

	NuGet.SemanticVersion Version

	System.String Title

	System.Collections.Generic.IEnumerable`1[System.String] Authors

	System.Collections.Generic.IEnumerable`1[System.String] Owners

	System.Uri IconUrl

	System.Uri LicenseUrl

	System.Uri ProjectUrl

	System.Uri ReportAbuseUrl

	Int32 DownloadCount

	Boolean RequireLicenseAcceptance

	Boolean DevelopmentDependency

	System.String Description

	System.String Summary

	System.String ReleaseNotes

	System.String Language

	System.String Tags

	System.Version MinClientVersion

	Boolean IsAbsoluteLatestVersion

	Boolean IsLatestVersion

	Boolean Listed

	System.Nullable`1[System.DateTimeOffset] Published

	System.String Copyright

	System.Collections.Generic.IEnumerable`1[NuGet.PackageDependencySet] DependencySets

	System.Collections.Generic.IEnumerable`1[NuGet.FrameworkAssemblyReference] FrameworkAssemblies

	System.Collections.Generic.IEnumerable`1[NuGet.IPackageAssemblyReference] AssemblyReferences

	System.Collections.Generic.ICollection`1[NuGet.PackageReferenceSet] PackageAssemblyReferences


Constructors
----------------
	Void .ctor(String)

	Void .ctor(Func`1, Func`1)

	Void .ctor(Stream)


Methods
----------------
	System.IO.Stream GetStream()

	Void ExtractContents(NuGet.IFileSystem, System.String)

	System.String GetPackageIdentifier(System.IO.Packaging.Package)

	System.Collections.Generic.IEnumerable`1[System.Runtime.Versioning.FrameworkName] GetSupportedFrameworks()

	System.Collections.Generic.IEnumerable`1[NuGet.IPackageFile] GetFiles()

	System.String ToString()

	Boolean Equals(System.Object)

	Int32 GetHashCode()

	System.Type GetType()
#+END_SRC 

**** Show all exported classes 

 - =$ pget.exe --class [asmFile]=

Example:

#+BEGIN_SRC text 
$ bin/pget.exe repo --files OxyPlot.Core | grep ".dll"
packages/OxyPlot.Core.1.0.0/lib/portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1+Xamarin.iOS10/OxyPlot.dll
packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.dll
packages/OxyPlot.Core.1.0.0/lib/net40-client/OxyPlot.dll
packages/OxyPlot.Core.1.0.0/lib/net40/OxyPlot.dll
packages/OxyPlot.Core.1.0.0/lib/sl5/OxyPlot.dll

$ bin/pget.exe asm --class packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.dll
OxyPlot.DelegateViewCommand`1[T]
OxyPlot.ElementCollectionChangedEventArgs`1[T]
OxyPlot.ManipulatorBase`1[T]
OxyPlot.DelegatePlotCommand`1[T]
OxyPlot.Element
OxyPlot.ElementCollection`1[T]
OxyPlot.Model
OxyPlot.TouchTrackerManipulator
OxyPlot.OxySizeExtensions

... ...

OxyPlot.Axes.AngleAxis
OxyPlot.Axes.Axis
OxyPlot.Axes.AxisChangedEventArgs
OxyPlot.Axes.CategoryAxis
OxyPlot.Axes.CategoryColorAxis
OxyPlot.Axes.ColorAxisExtensions
OxyPlot.Axes.LinearColorAxis
OxyPlot.Axes.DateTimeAxis
OxyPlot.Axes.LinearAxis
OxyPlot.Axes.MagnitudeAxis

... ...

OxyPlot.Annotations.Annotation
OxyPlot.Annotations.ArrowAnnotation
OxyPlot.Annotations.EllipseAnnotation
OxyPlot.Annotations.FunctionAnnotation
OxyPlot.Annotations.ImageAnnotation
OxyPlot.Annotations.PathAnnotation
OxyPlot.Annotations.PolylineAnnotation
OxyPlot.Conrec+RendererDelegate
OxyPlot.Reporting.TableOfContents+ContentItem
#+END_SRC

**** Show all exported non-abstract classes 

 - =$ pget.exe --classn [asmFile]=

Example:

#+BEGIN_SRC text 
$ bin/pget.exe asm --classn packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.dll
OxyPlot.DelegateViewCommand`1[T]
OxyPlot.ElementCollectionChangedEventArgs`1[T]
OxyPlot.DelegatePlotCommand`1[T]
OxyPlot.ElementCollection`1[T]
...
OxyPlot.CodeGenerationAttribute
OxyPlot.CodeGenerator
OxyPlot.OxyPalette
OxyPlot.Decimator
OxyPlot.CohenSutherlandClipping
OxyPlot.OxyPen
OxyPlot.XkcdRenderingDecorator
OxyPlot.OxyKeyGesture
OxyPlot.OxyMouseDownGesture
OxyPlot.OxyMouseWheelGesture
...
OxyPlot.Annotations.EllipseAnnotation
OxyPlot.Annotations.FunctionAnnotation
OxyPlot.Annotations.ImageAnnotation
OxyPlot.Annotations.PolylineAnnotation
OxyPlot.Conrec+RendererDelegate
OxyPlot.Reporting.TableOfContents+ContentItem
#+END_SRC

**** Show all exported abstract classes 

 - =$ pget.exe --abstract [asmFile]=

Example:

#+BEGIN_SRC 
$ bin/pget.exe asm --abstract packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.dll
OxyPlot.ManipulatorBase`1[T]
OxyPlot.Element
OxyPlot.Model
OxyPlot.IController
OxyPlot.IViewCommand
OxyPlot.IViewCommand`1[T]
OxyPlot.IView
OxyPlot.IPlotController
OxyPlot.IPlotElement
OxyPlot.IPlotModel
OxyPlot.OxySizeExtensions
OxyPlot.OxyInputEventArgs
...
OxyPlot.HashCodeBuilder
OxyPlot.XmlWriterBase
OxyPlot.BinaryReaderExtensions
OxyPlot.StreamExtensions
OxyPlot.StringHelper
OxyPlot.FractionHelper
...
OxyPlot.Axes.IColorAxis
OxyPlot.Axes.ColorAxisExtensions
OxyPlot.Axes.AxisRendererBase
OxyPlot.Annotations.ShapeAnnotation
OxyPlot.Annotations.TextualAnnotation
OxyPlot.Annotations.Annotation
OxyPlot.Annotations.PathAnnotation

#+END_SRC

**** Show all exported interfaces 

 - =$ pget.exe --interface [asmFile]=

Example:

#+BEGIN_SRC 
$ bin/pget.exe asm --interface packages/OxyPlot.Core.1.0.0/lib/net45/OxyPlot.dll
OxyPlot.IController
OxyPlot.IViewCommand
OxyPlot.IViewCommand`1[T]
OxyPlot.IView
OxyPlot.IPlotController
OxyPlot.IPlotElement
OxyPlot.IPlotModel
OxyPlot.ICodeGenerating
OxyPlot.IDataPointProvider
OxyPlot.IRenderContext
OxyPlot.IExporter
OxyPlot.IImageDecoder
OxyPlot.IImageEncoder
OxyPlot.IPlotView
OxyPlot.Series.IScatterPointProvider
OxyPlot.Series.IStackableSeries
OxyPlot.Reporting.IReportWriter
OxyPlot.Axes.IColorAxis
#+END_SRC

**** Show all exported namespaces 

 - =pget.exe asm --namespace [asmFile]=

or

 - =pget.exe asm --ns [asmFile]=

Example:

#+BEGIN_SRC text 
  $ bin/pget.exe asm  --namespace /usr/lib/mono/4.5-api/System.Xml.dll
  System.Xml.Xsl.Runtime
  System.Xml
  System.Xml.XmlConfiguration
  System.Xml.Resolvers
  System.Xml.Schema
  System.Xml.Serialization
  System.Xml.Serialization.Advanced
  System.Xml.Serialization.Configuration
  System.Xml.XPath
  System.Xml.Xsl


  $ bin/pget.exe asm  -ns /usr/lib/mono/4.5-api/System.Xml.dll
  System.Xml.Xsl.Runtime
  System.Xml
  System.Xml.XmlConfiguration
  System.Xml.Resolvers
  System.Xml.Schema
  System.Xml.Serialization
  System.Xml.Serialization.Advanced
  System.Xml.Serialization.Configuration
  System.Xml.XPath
  System.Xml.Xsl

#+END_SRC

**** Show all types within an exported namespace

#+BEGIN_SRC text 
  $ bin/pget.exe asm  --namespace /usr/lib/mono/4.5-api/System.Xml.dll
  System.Xml.Xsl.Runtime
  System.Xml
  System.Xml.XmlConfiguration
  System.Xml.Resolvers
  System.Xml.Schema
  System.Xml.Serialization
  System.Xml.Serialization.Advanced
  System.Xml.Serialization.Configuration
  System.Xml.XPath
  System.Xml.Xsl

  $ bin/pget.exe asm  --namespace /usr/lib/mono/4.5-api/System.Xml.dll System.Xml
  System.Xml.ConformanceLevel
  System.Xml.DtdProcessing
  System.Xml.EntityHandling
  System.Xml.NamespaceHandling
  System.Xml.NewLineHandling
  System.Xml.ReadState
  System.Xml.ValidationType
  System.Xml.WhitespaceHandling
  ...
  System.Xml.XmlNodeType
  System.Xml.XmlQualifiedName
  System.Xml.XmlResolver
  System.Xml.XmlSecureResolver
  System.Xml.XmlUrlResolver
  System.Xml.XmlXapResolve


  $ bin/pget.exe asm  --type /usr/lib/mono/4.5-api/System.Xml.dll System.Xml.XmlNode

  Type Info:

    Name:           XmlNode
    Full Name:      System.Xml.XmlNode
    Namespace:      System.Xml
    Module:         System.Xml.dll
    Base Type:      System.Object

  Predicates

    Class:          True
    Abstract Class: True
    Primitive       False
    Array:          False
    Interface       False   
    Enum            False
    Public          True
    Visible         True
    
                          

  Fields
  ----------------

  Properties
  ----------------
      System.String Name

      System.String Value

      System.Xml.XmlNodeType NodeType

      System.Xml.XmlNode ParentNode

  ...

  Constructors
  ----------------

  Methods
  ----------------
      System.Xml.XPath.XPathNavigator CreateNavigator()

      System.Xml.XmlNode SelectSingleNode(System.String)

      System.Xml.XmlNode SelectSingleNode(System.String, System.Xml.XmlNamespaceManager)

  ...
#+END_SRC

*** Show System Information 

 - =$ pget.exe --system=

Windows:

#+BEGIN_SRC text 
  e:/projects/pget.fsharp $ bin/pget.exe --system
  System Information

    System Version            v4.0.30319
    System Directory          C:\Windows\system32
    Runtime Directory         C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    System Configuration File C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config
    OS Version                Microsoft Windows NT 6.2.9200.0
    Machine Name              DESKTOP-FDD38CU
    64-bit Operating system   True
    Number of processors      4

  Special Directories

    System.Environment.SpecialFolder.CommonApplicationData 
    C:\ProgramData

    System.Environment.SpecialFolder.ApplicationData       
    C:\Users\arch\AppData\Roaming

    System.Environment.SpecialFolder.LocalApplicationData  
    C:\Users\arch\AppData\Local

#+END_SRC

Linux: 

#+BEGIN_SRC text 

#+END_SRC
*** Generate GUID

 - =$ pget.exe --guid=

Example:

#+BEGIN_SRC sh
  $ bin/pget.exe --guid
  c4969f50-7a17-4f8f-ac9d-d783a9a8f8d4
#+END_SRC
** TODO Todolist 

 - [ ] - Improve display of F# types.
 - [ ] - Improve error handling
 - [ ] - Query types and XML documentation.
 - [ ] - Add more commands to manipulate and query fsproj files.
 - [ ] - Create an Emacs client for pget.exe. 
 - [ ] - MAYBE: Add support to a cached nuget repository.
 - [ ] - MAYBE: Add interactive shell.
 - [ ] - MAYBE: Add Windows Forms display.

* Pget.dll

Pget.dll is a F# library that provides a high level interface and
functional wrappers to NuGet.Core API.


